JS рандомайзер чисел
htmlacademy-javascript/465875-keksobooking-22 pull request #2
Opened 2021-02-02 07:41 UTC by kalaganov5

2021-02-02 13:47 UTC, nikkypizza requested changes

2021-02-02 13:47 UTC, nikkypizza commented on js/main.js
> +    }
Если ты уберешь **Math.floor** из **getRandomNumber**, то от этих 8 строк можно будет избавиться. Очень уж намудрил

2021-02-02 14:39 UTC, kalaganov5 commented on js/main.js
> +    }
По началу так сделал, столкнулся с проблемой, если вызываю `getRandomNumber` он выдает к примеру число `1.5790360752164192` а мы обрезаем до 4 символов, после запятой получается `1.5790`, то автоматически остается `1.579` убирая 0 в конце, при преобразование в число.

Как вариант решения думал повторно запускать `getRandomNumber`, чтобы 0 на конце (в том количестве символов после запятой) не было. Но решил что цикл который генерирует, более интересным решением)

Пример работы функции
`Number(
  (1 + Math.random() * (2 + 1 - 1)
  ).toFixed(2)
);`
Вернёт: 2.8
`Number(
  (1 + Math.random() * (2 + 1 - 1)
  ).toFixed(2)
);`
Вернёт: 1.88

Скрин https://s.mail.ru/HzZy/6TuuJWVjq

Как тогда лучше поступим?

2021-02-02 14:43 UTC, kalaganov5 commented on js/main.js
> +  let randomNumber;
Так поступил чтобы функция "была проще" и выход из функции был только один. А затем переменная меняет тип и значение

2021-02-02 14:48 UTC, kalaganov5 commented on js/main.js
> +  }
Здесь поступил также, чтобы выход из функции был только один, 
Да в этом случае сделаю лучше `return getRandomNumber(min, max);`

И в случае ошибки что то вроде `throw new Error('названиеФункции — что пошло не так');` как предложил выше

2021-02-02 14:54 UTC, kalaganov5 commented on js/main.js
> +const getRandomNumber = function (numberMin, numberMax) {
> getRandomNumber и getRandomInteger = одно и то же по названию, в чем разница?

Изначальная логика было что приписка `Integer`, это целое число, хотя по факту обе функции возвращают целое число

Да названия на функции поправлю

2021-02-02 16:23 UTC, nikkypizza commented on js/main.js
> +    }
Да, так и есть, необязательные нули сокращаются у чисел. Ну, из соображений точному соответствию ТЗ можешь оставить как есть только давай подсократим тело функции и будем использовать [операторы присваивания](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Assignment_Operators) вместо переопределения. Также необязательное дублирование, можно описать в одну строку без потери читаемости:
```
floatingPointNumber = getRandomNumber(1, 9) / factor;
```

2021-02-02 16:23 UTC, nikkypizza commented on js/main.js
> +  }
Выход ведь и так только один, не вижу как это связано с созданием одноразовой переменной.

-----
Еще хороший паттерн — сперва проверять на ошибки, а потом уже выполнять тяжелую работу. 

В **getRandomNotInteger** сделано верно, а тут наоборот, сперва выполняется целевое действие, а только после этого проверятся норм ли все с аргументами

2021-02-03 07:25 UTC, nikkypizza commented on js/main.js
> +    }
Также для избегания цикла можешь менять лишь последнее число на рандомный не 0, тогда число не будет обрезаться по нулю

2021-02-03 07:32 UTC, kalaganov5 commented on js/main.js
> +    }
Принято

2021-02-03 19:53 UTC, kalaganov5 commented on js/main.js
> +  }
Получилось с одной стороны громоздко, но легче того цикла, да и запускается только если есть 0 на конце в дробном числе)

2021-02-04 07:46 UTC, nikkypizza approved these changes

2021-02-04 07:46 UTC, nikkypizza commented on js/main.js
> +    throw new Error('getRandomWholeNumber — что пошло не так');
Не очень-то информативно)

2021-02-04 07:46 UTC, nikkypizza commented on js/main.js
> +  if(randomNumber.slice(-1) === '0' && ((randomNumber ^ 0) === randomNumber) === false) {
Советую воздерживаться от битовых операций, они могут быть ресурсозатратными, вдобавок мало разработчиков их поймут с одного взгляда и придется разбираться и гуглить. Тут можешь узнать дробное ли число проверив остаток от деления на единицу, такой подход более расхожий
```suggestion
  if(randomNumber.slice(-1) === '0' && randomNumber % 1 !== 0) {
```

2021-02-04 07:46 UTC, nikkypizza commented on js/main.js
> +    randomNumber = randomNumber.substring(0, randomNumber.length - 1) + getRandomWholeNumber(1, 9) + randomNumber.substring(1 + randomNumber.length - 1);
Зачем прибавлять `randomNumber.substring(1 + randomNumber.length - 1)` в конце?

2021-02-04 07:46 UTC, nikkypizza commented on js/main.js
> +  return Number(randomNumber);
К слову, есть упрощенный способ приведения к числу
```suggestion
  return +randomNumber;
```

2021-02-04 07:46 UTC, merged

2021-02-04 07:51 UTC, kalaganov5 commented on js/main.js
> +    throw new Error('getRandomWholeNumber — что пошло не так');
Принято)